BROKER_HOST = "192.168.1.47"
BROKER_PORT = 5672
BROKER_USER = "beka"
BROKER_PASSWORD = "beka"
BROKER_VHOST = "vhost_beka"

CELERY_RESULT_BACKEND = "amqp"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_IMPORTS = ("Siren-GA.main",)